### ISSUE TITLE
Insecure users tylko dla NG ludkow

### ISSUE THREAD

**Issue by mwsteb** [netguru/access#62]
Jak klikam 'show diff' to chce widziec diffa, a nie przewijac 3 strony userow-klientow/ext-devow bez 2fa. 

1) pokazujmy tylko ludkow z brakujacym 2fa jesli maja mejal na domenie @netguru
2) jesli bardzo potrzebujemy tez reszty, ukrywajmy ich by default i pokazujmy po zaznaczeniu checkboxa/kliknieciu w przycisk.

Thoughts?

**Comment by siepet** [comment]
Może po prostu drugi widok po insecure users?

**Comment by mwsteb** [comment]
Tez opcja, pytanie tylko czy tego w ogole potrzebujemy? Czy prosimy klientow zeby robili 2fa? Przeciez w 99% oni i tak nie maja zadnych dostepow. W zasadzie widze zastosowanie tylko przy external devach.

**Comment by siepet** [comment]
Najczęsciej kto jest na supporcie zazwyczaj prosił klientów o włączenie 2FA.

**Comment by siepet** [comment]
@lubieniebieski jeśli jest to: https://github.com/netguru/access/pull/64, to czy nie można issue #62 zamknąć?

**Comment by lubieniebieski** [comment]
tak, masz racje @siepet, zamykam - tam możesz od razu code review machnąć
